# Generated by Django 2.0.9 on 2018-12-20 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatter', '0002_auto_20181219_0610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='message_id',
        ),
    ]
